## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [26]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = 3
arr = list(np.arange(1, 4))
np.array(arr*n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
arr = np.zeros((10, 10))

arr[0, :], arr[:, 0], arr[:, 9], arr[9, :] = [1, 1, 1, 1]
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
arr = np.zeros((8, 8))

arr[0::2, 1::2], arr[1::2, 0::2] = [1, 1]
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [56]:
def ij_matrix(n):
    i, j = np.ogrid[:n, :n]
    return i+j
ij_matrix(10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [57]:
vector1 = np.array([1, 3, 5, 7])
vector2 = np.array([[1], [3], [5], [7]])
A = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
B = np.array([[1, 3], [2, 4], [5, 7], [6, 8]])

print(np.dot(vector1, vector2), 'Умножение двух векторов\n')
print(np.dot(A, vector2), 'Умножение вектора и матрицы\n')
print(np.dot(A,B), 'Умножение двух матриц')

[84] Умножение двух векторов

[[ 84]
 [100]] Умножение вектора и матрицы

[[ 74 106]
 [ 88 128]] Умножение двух матриц


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [58]:
num_of_steps = 1/0.05

cosines = np.cos(np.linspace(0, 1, int(num_of_steps)))
sines = np.sin(np.linspace(0, 1, int(num_of_steps)))
result = list(cosines) + list(sines)
result.sort()
print(result)

[0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.5403023058681398, 0.547143146340223, 0.5838216399741468, 0.5904198559291864, 0.625724112908743, 0.6320614309590333, 0.6658936781316236, 0.6719525474315213, 0.7042190882928544, 0.7099827291448582, 0.7405942033261461, 0.7460466536513234, 0.7749182843977933, 0.7800444439418607, 0.8070962728972044, 0.8118819450498316, 0.8370390536963741, 0.8414709848078965, 0.8646637019492132, 0.8898937127472434, 0.912659212995635, 0.9328971549228098, 0.9505514906876966, 0.9655733276010717, 0.9779210635311101, 0.9875605021181478, 0.9944649474795756, 0.9986152781425827, 1.0]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [59]:
A = 4*np.random.rand(3,5)-1
A

array([[ 2.47483362,  0.19467517,  0.35040476,  0.34714552,  1.64853052],
       [ 2.74692839,  0.71008781,  1.70027431,  2.97427229, -0.69435713],
       [ 1.64937308,  1.0472098 ,  0.31610121,  1.19861079, -0.14260747]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [60]:
sum = np.sum(A)
sum_col = np.sum(A, axis = 0)
sum_str = np.sum(A, axis = 1)
mean = np.mean(A, axis = 1)
dispersion = np.var(A, axis = 1)
std_deviation = np.std(A, axis = 1)
print(f'Сумма всех элементов: {sum}\nCумма внутри строк: {sum_str}\nСумма внутри столбцов: {sum_col}\n' \
      f'Средние значения: {mean}\nДисперсия: {dispersion}\nСтандартное отклонение: {std_deviation}')

Сумма всех элементов: 16.521482670426487
Cумма внутри строк: [5.01558959 7.43720567 4.06868742]
Сумма внутри столбцов: [6.87113509 1.95197278 2.36678028 4.5200286  0.81156592]
Средние значения: [1.00311792 1.48744113 0.81373748]
Дисперсия: [0.81848369 1.84135897 0.41263224]
Стандартное отклонение: [0.90470088 1.35696683 0.64236457]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [61]:
for i in range(len(A)):
    A[i, :] = (A[i, :] - np.mean(A[i])) / np.std(A[i])
A

array([[ 1.62674285, -0.89360225, -0.72146846, -0.72507103,  0.71339889],
       [ 0.92816363, -0.57286096,  0.15684479,  1.09570192, -1.60784938],
       [ 1.30087437,  0.36345765, -0.77469447,  0.59915091, -1.48878846]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [62]:
col = A[:, 3]
sorted = np.argsort(A[:, 3])
temp = np.zeros((3,))
for i in range(3):
    temp[i] = col[sorted[i]]
A[:, 3] = temp
A

array([[ 1.62674285, -0.89360225, -0.72146846, -0.72507103,  0.71339889],
       [ 0.92816363, -0.57286096,  0.15684479,  0.59915091, -1.60784938],
       [ 1.30087437,  0.36345765, -0.77469447,  1.09570192, -1.48878846]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [63]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))

print(f'Матрица B: {B}\n\nМатрица C: {C}')

#Матрицы B и C схожи тем, что у них одинаковое число измерений (= 2) и тип данных (float64).
#Отличия - хранящаяся в них значения и размеры матриц (B размер - (5,5), C - (3,3)) 
#и количествами элементов (25 и 9 соответсвенно).

Матрица B: [[ 5.20005417 -1.51255705 -2.03584621  0.80197651 -2.26855753]
 [-1.51255705  1.25879613  0.27328695  0.70293618 -0.25753227]
 [-2.03584621  0.27328695  1.14526855 -0.23174464  0.38647859]
 [ 0.80197651  0.70293618 -0.23174464  2.08527249 -3.11187764]
 [-2.26855753 -0.25753227  0.38647859 -3.11187764  5.31060866]]

Матрица C: [[5.         0.32716991 0.4937574 ]
 [0.32716991 4.15841912 3.92794518]
 [0.4937574  3.92794518 5.84158088]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [65]:
np.sum(np.diagonal(B)) + np.sum(np.diagonal(C))


30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [67]:
#det_A = np.linalg.det(A) - применить нельзя, так как матрица A - прямоугольная.
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)
wB, vB = np.linalg.eig(B)
wC, vB = np.linalg.eig(C)

print(f'Ранг матрицы А: {rank_A}\nДетерминант матрицы B: {det_B}\nРанг матрицы B: {rank_B}\n' \
      f'Спектр матрицы B: {wB}\nДетерминант матрицы C: {det_C}\nРанг матрицы C: {rank_C}\n' \
      f'Спектр матрицы C: {wC}\n')

#Матриц A, B, C с одинаковым рангом. 
#Вывод: При умножении матрицы в любом порядке на себя транспонированную ранг не меняется.
#Будет меняться только детерминант и собственные значения.

Ранг матрицы А: 3
Детерминант матрицы B: -1.0170552419787478e-30
Ранг матрицы B: 3
Спектр матрицы B: [ 9.10186456e+00  4.91601424e+00 -2.93905555e-16  9.82121204e-01
  2.85782620e-16]
Детерминант матрицы C: 43.944910880895925
Ранг матрицы C: 3
Спектр матрицы C: [9.10186456 4.91601424 0.9821212 ]



16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [19]:
#Обязательно решить 9 номер и шестой номер
#np.random.seed(1032201715)
#np.random.randint(9)

In [25]:
np.random.seed(1032201715)
np.random.randint(9)

6

In [80]:
#Номер 6
def f(x):
    return (np.cosh(3*x))**2

def integral(f, a, b, dx):
    N = int((b-a) / dx)  #количество шагов
    xk = np.linspace(a, b, N)  #точки
    rectan = dx*np.sum(f(xk))  #Метод прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  #Методом трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  #Метод Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

#Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
#Вывод: значение интеграла функции f(x) на отрезке [a;b]

anal_solution = np.float64(0.468905)  #Аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [0; 1/3]")

for i in range(6):
    print(integral(f, 0, np.float64(1/3), 0.1 * 0.1**i))

#Вывод: При уменьшении dx уменьшается разница между аналитическим решением и тремя численными значениями выше. 
#Это происходит из-за того, что увеличивается число шагов N и число точек xk. 

0.468905 - аналитическое решение функции f(x) на отрезке [0; 1/3]
0.4652638162949438, 0.30084555447390965, 0.11579434848876498 при шаге интегрирования 0.1
0.4671487651967749, 0.45024777731922777, 0.41986705984499595 при шаге интегрирования 0.010000000000000002
0.46872087313005106, 0.4670303287072936, 0.46386914000883656 при шаге интегрирования 0.0010000000000000002
0.46888653593671314, 0.4687174810489361, 0.4684001373512136 при шаге интегрирования 0.00010000000000000003
0.468903183365795, 0.46888627787657183, 0.4688545312653783 при шаге интегрирования 1.0000000000000003e-05
0.4689048489169453, 0.4689031583680226, 0.4688999835844958 при шаге интегрирования 1.0000000000000004e-06


In [81]:
#Номер 9
def f(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def integral(f, a, b, dx):
    N = int((b-a) / dx)  #количество шагов
    xk = np.linspace(a, b, N)  #точки
    rectan = dx*np.sum(f(xk))  #Метод прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  #Метод трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  #Метод Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

#Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
#Вывод: значение интеграла функции f(x) на отрезке [a;b]

anal_solution = np.float64(1.110720734539591561753970247515173)  # аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [3/4;2]")

for i in range(6):
    print(integral(f, np.float64(3/4), 2, 0.1 * 0.1**i))
    
#Вывод: При уменьшении dx уменьшается разница между аналитическим решением и тремя численными значениями выше. 
#Это происходит из-за того, что увеличивается число шагов N и число точек xk. 

1.1107207345395915 - аналитическое решение функции f(x) на отрезке [3/4;2]
0.8238512126812755, 0.8098258036743812, 0.7737705910624484 при шаге интегрирования 0.1
1.0322244184751246, 1.0312903460191785, 1.0212859253328779 при шаге интегрирования 0.010000000000000002
1.088756499376807, 1.088627061795969, 1.072525102066485 при шаге интегрирования 0.0010000000000000002
1.1041017867496095, 1.1040446838813676, 1.0989731743454727 при шаге интегрирования 0.00010000000000000003
inf, 1.1086409328324405, 1.1070394070810448 при шаге интегрирования 1.0000000000000003e-05


C:\Users\Пользователь\AppData\Local\Temp\ipykernel_7872\1870802619.py:3: RuntimeWarning: divide by zero encountered in divide
  return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)


inf, 1.1100661882097627, 1.1095599697750977 при шаге интегрирования 1.0000000000000004e-06
